### ISSUE TITLE
spec.sasl.mechanism from YAML is ignored if TOPICCTL_SASL_USERNAME or TOPICCTL_SASL_PASSWORD is set

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [segmentio/topicctl#54] opened 2021-11-15 04:56 UTC
We are using `topicctl` with environment variables to avoid hardcoding them in a `cluster.yaml` file. This causes `topicctl` to ignore the `sasl.mechanism` field in the yaml file.

It would be nice to be able to read credentials from the environment while also reading the mechanism from the config file. An in-between fix would be to listen to an environment variable for SASL mechanism also.

This applies to the `topicctl get topics` command, but doesn't seem to cause problems for `topicctl apply`.

**Comment by yolken-segment** [comment] 2021-11-17 02:58
Hmm, I'm not able to reproduce this. Can you attach a sanitized version of your cluster config?

**Comment by yolken-segment** [comment] 2021-11-18 00:41
This has been fixed in https://github.com/segmentio/topicctl/pull/55. Thanks for the report!

**Closed by yolken-segment** 2021-11-18 00:41 UTC

**Comment by JackKelly-Bellroy** [comment] 2021-11-18 00:50
Confirmed working. Thanks for the fast turnaround!
